version: '3'

services:
  mariadb:
    image: mariadb/server:10.3
    restart: always
    container_name: mariadb
    hostname: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: brainlabs
      MARIADB_ROOT_HOST: "%"
      MARIADB_USER: admin
      MARIADB_PASSWORD: brainlabs
      TZ: "Asia/Jakarta"
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mariadb:
    driver: local