version: '3'

services:
  my-app:
    build:
      context: .
      dockerfile: deployment/dockerfiles/dockerfile-local
    working_dir: /go/src/github.com/aryayunanta-ralali/shorty
    container_name: my-app
    hostname: my-app
    networks:
      - code-network
    volumes:
      - .:/go/src/github.com/aryayunanta-ralali/shorty
    ports:
      - 8081:8081
    depends_on:
      - mariadb

  mariadb:
    image: mariadb/server:10.3
    restart: always
    container_name: mariadb
    hostname: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: brainlabs
      MARIADB_ROOT_HOST: "%"
      MARIADB_USER: admin
      MARIADB_PASSWORD: brainlabs
      TZ: "Asia/Jakarta"
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - code-network

volumes:
  mariadb:
    driver: local

networks:
  code-network:
    driver: bridge